server:
  port: 8080
  servlet:
    context-path: "/api/v1"
spring:
  application:
    name: "SpringSecurityMaster"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: postgres
    password: postgres
    driver-class-name: "org.postgresql.Driver"
#    url: "jdbc:h2:mem:test"
#    username: "sa"
#    password: "pass"
#    driverClassName: "org.h2.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
