### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### POST all channels
POST http://localhost:9000/api/channels
Content-Type: application/json

{
  "name": "",
  "group": "",
  "page": 1,
  "size": 5
}

### GET channel with id 1
GET http://localhost:9000/channels/1889

### GET channel by group
GET http://localhost:9000/api/channel-groups