pluginManagement {
    repositories {
        //mavenLocal()
        gradlePluginPortal()
    }
}

buildCache {
    local {
        directory = new File(rootDir, 'build-cache')
    }
}

rootProject.name = 'IPTVApp'

include ':app-service'
include ':model'
include ':usecase'
include ':rest-consumer'
include ':reactive-web'
include ':iptv-helper'
include ':r2dbc-postgresql'

project(':app-service').projectDir = file('./applications/app-service')
project(':model').projectDir = file('./domain/model')
project(':usecase').projectDir = file('./domain/usecase')
project(':rest-consumer').projectDir = file('./infrastructure/driven-adapters/rest-consumer')
project(':reactive-web').projectDir = file('./infrastructure/entry-points/reactive-web')
project(':iptv-helper').projectDir = file('./infrastructure/helpers/iptv')
project(':r2dbc-postgresql').projectDir = file('./infrastructure/driven-adapters/r2dbc-postgresql')